### ISSUE TITLE
As musician I can start collect my band's scores metadata

### ISSUE THREAD

**Issue by petrus-v** [petrus-v/band-management#2]
## Goals

As musician I can collect scores related to my different bands in order to organize and help me to find it.

## Description

First basic step to get opportunity to setup and validate technical choices/

## Objectives

- [x] As band admin I can invite new musician (no email but could be nice to generate token uri that allow user to set up his account)
- [x] As musician I can connect to the service using my email address/password
- [x] As musician I can create bands and other musicians
- [x] As musician I can create musics and scores

## Tasks

- [x] Create base models

<img width="1632" alt="Image" src="https://github.com/user-attachments/assets/ec7168a8-872b-49e3-b3bc-49e520d3bec3" />

- [x] Setup CI => https://github.com/petrus-v/band-management/pull/3
- [x] Start user interface - a  responsive webapp- to manage those data => https://github.com/petrus-v/band-management/pull/5
- [x] Add user model + login page to connect with existing db account => https://github.com/petrus-v/band-management/pull/6
- [x] Import scores https://github.com/petrus-v/band-management/pull/9
- [x] add band is admin config parameter
- [x] allow to edit band where I'm admin
- [x] display only scores with missing data
  - [x] no music set
- [x] Link musics to bands
- [x] Add musician (and instruments???) to a band
- [x] search/sort score by:
  - [x] band
  - [ ] music metadata (dance / author / compositor) 

to post-pone ?

- [ ] ask to join an existing band
- [ ]
